//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZamenaKursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Room { get; set; }
        public string Time { get; set; }
        public string Teacher { get; set; }
        public int DayOfWeek { get; set; }
        public int LessonNumber { get; set; }
        public string GroupName { get; set; }
    }
}
